### PR TITLE
Add configure command to bridgetown to run packaged automations

### PR DESCRIPTION
**Pull request by ayushn21**
This is a 🙋 feature or enhancement.

- [x] I've added tests (if it's a bug, feature or enhancement)
- [x] I've adjusted the documentation (if it's a feature or enhancement)
- [x] The test suite passes locally (run `script/cibuild` to verify this)

## Summary

This PR adds a `configure` command to `bridgetown`. The purpose of this would be to allow us to package automations with bridgetown itself so common tasks such as installing TailwindCSS or setting up other PostCSS plugins or combinations thereof can be done easily. 

I've added a `configurations` folder where all packaged automations can go. The `configure` command will just look in this directory for a file that matches the argument passed in; and if one exists, it will invoke the `apply` command passing that file as an argument.

Configurations can also be applied with `bridgetown new` using the `-c` flag. 

## TODO

- [x] Clean up code and improve syntax if/where possible
- [x] Compile a list of automations we want to package
- [x] Implement and add those automations
- [x] Add tests
- [x] Add docs

## Context

https://github.com/bridgetownrb/bridgetown/issues/207#issuecomment-749609164

### CODE REVIEW

**Comment by jaredcwhite** [comment]
Holy guacamole, that was fast. This looks very cool @ayushn21 …as far as naming goes, addin? addon? to-may-to? tom-ah-to? We can workshop it a bit, but the idea is sound.

**Comment by jaredcwhite** [comment]
Could also somehow tie into `bridgetown new` so you could run N additional installations after the site's created, just like the `--apply` option

**Comment by ayushn21** [comment]
Cheers @jaredcwhite! Yeah I'll have a think about the naming over the next few days. Figured since I broke my resolution to stay away from code until 2021 today; I might as well make the most of it!! 

> Could also somehow tie into bridgetown new so you could run N additional installations after the site's created, just like the --apply option

Yeah for sure. Good idea!

**Comment by DamnedScholar** [comment]
"Automata" would be a fun name, those being the actors that perform automations.

**Comment by ayushn21** [comment]
Thanks @DamnedScholar, that's an interesting word. Hadn't heard it before!

However, thinking about this is bit more I'm inclined to rename the command `bridgetown configure`. Setting up stuff like Tailwind or an omakase postcss setup etc feel more like things we're configuring rather than things we're installing. `bridgetown configure tailwind` sounds more appropriate in my opinion.

So if there's no objections I think I'll rename the command to `configure` and the entities we're configuring can just be called `configurations`.

**Comment by ayushn21** [comment]
I think I'm pretty much there with the implementation of the `configure` command. I think the next step for this PR should be adding in a few common configurations. `tailwind` and `netlify` I reckon are no-brainers. I'd also like to include an omakase PostCSS setup, though this might be a bit more tricky to get some kind of consensus on!

@jaredcwhite What do you reckon is the best next step with regard to the configurations we want to include?

I also need to update the docs. I think the best way would be to create new page in the `Configuration` section right after "Automations". 

Screenshot 2021-01-03 at 10 36 49 pm

**Comment by ayushn21** [comment]
I reckon this one's good to go now. I've added in all the automations from [bridgetownrb/automations](http://github.com/bridgetownrb/automations) so I guess we can deprecate the repo once this is released.

I've also added in a `tailwindcss` configuration.

I still believe we absolutely must have a Bridgetown recommended PostCSS plugin setup. I think we should do that in a separate PR though as it'll be tricky to find consensus on the plugins that should be included.

I've added a new docs page called "Bundled Configurations" that describes this feature.

@jaredcwhite let me know what you think and if you'd like any changes :)

**Comment by jaredcwhite** [comment]
Quick comment: I think we add should add Turbo and Stimulus (separately) as configurations. Arguably more important than Swup, so seems logical. Stimulus in particular would need a bit of a JS harness to set up… @ParamagicDev put together an automation a while back that could prove useful here. https://github.com/ParamagicDev/bridgetown-automation-stimulus/blob/master/bridgetown.automation.rb 

Let me know if you'd like any assistance.

**Comment by ayushn21** [comment]
Yup I agree. Only added in Swup because it was already in the bridgetown/automations repo :) 

I'll add in both Stimulus and Turbo as well 👍.

**Comment by jaredcwhite** [comment]
Code-wise this all looks great to me. Feel free to merge in any time. :+1:

**Pull request merged**
