### PR TITLE
feat: Add hash attributes functionality to view tag helpers

### LINKED ISSUE #537: feat: Add hash attributes functionality to view tag helpers
## Summary
In Rails and other static site generators like Middleman, you can pass a data hash into helpers like `link_to` and `image_tag` whose key-value pairs will then be rendered as individual data attributes in the generated HTML.  In Bridgetown, this will output a singular data attribute whose value is a hash-structured, JSON-esque string of all the key/value pairs (i.e. `data="{:id=>"123", :name="John", :"created-at"=>"2022-04-20 13:11:31 -0400"}"`).

## Motivation
This will be nice in more complex situations where `link_to` is required over a simple `<a>` tag and data attributes need to be attached.

## Reference-level explanation
Rails' `<%= link_to %>` lets you pass in optional arguments (generally HTML attributes) including, but not limited to, data attributes.  The way in which you would pass in the data attributes would be structured as a hash, preferably in the Ruby > 1.9 syntax (i.e. `data: { id: '123', name: 'John', 'created-at': Time.now }`). See full example below:

This input:
```
<%= link_to 'About', '/about.html', data: { id: '123', name: 'John', 'created-at': Time.now } %>
```
would then output:
```
<a href="/about.html" data-id="123" data-name="John" data-created-at="2022-04-20 13:11:31 -0400">About</a>
```

## Drawbacks
None come to mind.

## Unresolved Questions
I don't know how possible this is, but it would be great to be able to use ActionView helpers from anywhere within the repo (where applicable).

### PR DESCRIPTION
**Pull request by DRBragg**
This is a 🙋 feature or enhancement.

## Summary

Adds the ability to pass a hash to `link_to` (or call `attributes_from_options` to use on any HTML tag) and have the key-value pairs be listed as HTML attributes.

Example:

```ruby
<%= link_to "Label", "/foo/bar", class: "classes", data: { controller: "testable", action: "testable#test" } %>
```
would return:
```html
<a href="/foo/bar" class="classes" data-controller="testable" data-action="testable#test">Label</a>
```
You also have the ability to pass a hash as a keys value and have the values keys merged with the parent key. So:
```ruby
<%= link_to "Label", "/foo/bar", class: "classes", data: { controller: "testable", action: "testable#test", testable: { target: "test_value", index_value: "1" } } %>
```
would return:
```html
<a href="/foo/bar" class="classes" data-controller="testable" data-action="testable#test" data-testable-target="test_value" data-testable-index-value="1">Label</a>
```
This is very helpful when using stimulus controllers.

If you wanted to use this on a different HTML tag you could do:
```ruby
<div <%= attributes_from_options(class: "classes", data: { controller: "testable", action: "testable#test" }) %>>Content</div>
```
and you'd be left with:
```html
<div class="classes" data-controller="testable" data-action="testable#test">Content</div>
```

Naming is hard so I'm definitely open to suggests (I sorta hate `attributes_from_options` TBH).

Let me know if anything isn't to your liking and I'm happy to adjust!

## Context

Close #537

### CODE REVIEW

**Comment by jaredcwhite** [comment]
Thanks @DRBragg! I hope to review shortly.

**Comment by jaredcwhite** [comment]
@DRBragg This looks good to me. I don't necessarily mind the naming there, but I'd be OK with making that a private method and finessing it more before the next release cycle.

Do you want to take a stab at documentation? Or I can merge in and add that. Let me know!

**Review by jaredcwhite — APPROVED** [review]

**Comment by DRBragg** [comment]
> @DRBragg This looks good to me. I don't necessarily mind the naming there, but I'd be OK with making that a private method and finessing it more before the next release cycle.
> 
> Do you want to take a stab at documentation? Or I can merge in and add that. Let me know!

I'm willing to take a crack at it, but TBH I'm not 100% sure the best place to put the documentation. I'm not even 100% sure the docs for `link_to` are 😅. If you point me in the right direction I'll (at least) get the ball rolling.

**Comment by jaredcwhite** [comment]
@DRBragg Sure, take a look in 

[bridgetown-website/src/_docs/template-engines/erb-and-beyond.md](https://github.com/bridgetownrb/bridgetown/blob/main/bridgetown-website/src/_docs/template-engines/erb-and-beyond.md)

under the `Link and URL Helpers` heading.

**Comment by DRBragg** [comment]
@jaredcwhite I'm so sorry for the delay on this! I started the documentation and then life went a bit sideways on me.  Let me know if I'm heading in the right direction with what I've added so far and I can take another crack at it over the weekend.

**Comment by jaredcwhite** [comment]
Seems like a good start to me @DRBragg! Maybe just elaborate a bit? Currently it's a little dense with jargon (I'm guilty of this myself…am trying to identify with newbies a bit more now when I write technical content).

**Comment by DRBragg** [comment]
> Seems like a good start to me @DRBragg! Maybe just elaborate a bit? Currently it's a little dense with jargon (I'm guilty of this myself…am trying to identify with newbies a bit more now when I write technical content).

Makes sense. I'll try to rewrite it a little more straight forward with more examples.

**Comment by DRBragg** [comment]
@jaredcwhite Not sure if the updated documentation is any better than the original. I definitely need more practice writing docs so thanks for the opportunity to work on this. Let me know if the current version works for you or if you'd like some changes.  I'll also run it by some folks at work who are better at phrasing things than I am to see if they have any suggestions.

Again, I really appreciate your patience on this PR. I'm sorry it's taking so long. It's been a weird few weeks for me.

**Comment by jaredcwhite** [comment]
Thanks @DRBragg! That's a great update, seems very clear and readable to me now. 👍

**Pull request merged**
