### PR TITLE
Fix class declaration keyword in liquid tags and helpers docs

### LINKED ISSUE #197: docs: Typos in docs/plugins/helpers#supporting-arguments
## Motivation

This page has several typos.

[plugins/helpers](https://www.bridgetownrb.com/docs/plugins/helpers#supporting-arguments)

## Suggestion
```diff
- def Helpers < SiteBuilder
+ class Helpers < SiteBuilder
```

### PR DESCRIPTION
**Pull request by ayushn21**
This is a 🔦 documentation change.

## Summary

Documentation fixes on the `plugins/tags` and `plugins/helpers` pages where it seems a class was declared with `def`. I've just replaced `def` with `class`.

This PR fixes #197

### CODE REVIEW

**Comment by jaredcwhite** [comment]
Thanks @ayushn21! Do you mind addressing #197 as well and we can fix it all together? (There must have been a typo in an initial example and then it propagated around other parts of the helpers/filters/tags docs… 😬)

**Comment by ayushn21** [comment]
Yup sure @jaredcwhite; will add those fixes in as well :)

**Comment by ayushn21** [comment]
I've just pushed the fixes for the helpers page as well :)

**Comment by jaredcwhite** [comment]
@ayushn21 Niiiice :+1:

**Pull request merged**
