### PR TITLE
feat: alias pager to paginator

### PR DESCRIPTION
**Pull request by ParamagicDev**
This is a 🙋 feature or enhancement.

## Summary

Aliases Pager to Paginator...wasnt sure where to get started adding tests for this. I couldnt find anything in the bridgetown-core test suite related to `pager`. I would love to expand more on this PR but need maybe a little more guidance.

## Context

Addresses #145

### CODE REVIEW

**Comment by jaredcwhite** [comment]
I was about to say take a look at the `bridgetown-paginate` gem in the monorepo, but…actually, there are no tests there. Ooopsie! So I guess this is fine for now. I would also like to get the `paginator` variable added to `RubyTemplateView` along with `site`, `page`, etc.

**Comment by ParamagicDev** [comment]
Okay now that I can work with 👍

**Comment by ParamagicDev** [comment]
@jaredcwhite Rather than messing around with core, I decided to just go into the paginate gem and alias the `newpage.pager = Paginator.new` to `newpage.pager = newpage.paginator = Paginator.new` Im not really sure where to test this out other than to spin up a new site and try it out and that just feels...wrong

**Comment by jaredcwhite** [comment]
Now I'm waffling on this entirely…the `pager` term is a holdover from Jekyll and nothing in the codebase outside the pagination gem directly uses `pager` to the best of my knowledge. Wondering if we should just rename to `paginator` outright (but that could potentially break a few sites out in the wild…)

**Comment by ParamagicDev** [comment]
Perhaps we mark it deprecated and provide a warning in this release, and then in the following release remove it? @jaredcwhite

**Comment by jaredcwhite** [comment]
That's for sure the way to go, @ParamagicDev. So let's make `paginator` the real name and `pager` can be the alias, and we'll remove in a future release. 👍

**Pull request merged**
