### PR TITLE
Bump up esbuild version in new template and on the BT site

### PR DESCRIPTION
**Pull request by jaredcwhite**
This bumps up the esbuild dep version 0.15.x.

### CODE REVIEW

**Comment by andrewmcodes** [comment]
@jaredcwhite this might be of some interest to you https://github.com/andrewmcodes/bridgetown-esbuild-minifySyntax#readme

**Comment by KonnorRogers** [comment]
I haven't had time to look at this yet, but be careful with this one, 0.14.x -> 0.15.x I saw a breaking change with using relative file paths without "./"

I upgraded one of my library and had to add:

`"." + path.sep`

0.15.x -> https://github.com/KonnorRogers/bridgetown-quick-search/blob/df061f2fbdaddac2848f03807f01796fd356000e/esbuild.config.js#L12

0.14.x -> https://github.com/KonnorRogers/create-konnor-app/blob/fde3ec3003f2bbce77ce5ddbc2de85c78c6c3b0d/src/templates/browser-project/esbuild.config.js#L9

**Comment by andrewmcodes** [comment]
> I haven't had time to look at this yet, but be careful with this one, 0.14.x -> 0.15.x I saw a breaking change with using relative file paths without `"./"`
> 
> 
> 
> I upgraded one of my library and had to add:
> 
> 
> 
> `"." + path.sep`
> 
> 

I've been running `0.15.12` since it came out without issue until I tried switching to typescript and got an error about relative paths similar to what @KonnorRogers mentions. 

```
Without the leading "./", the path "frontend/javascript/index.js"
  is being interpreted as a package path instead
```

but this change in the config fixed it and I haven't had any other issues. 

```diff
-entryPoints: ["frontend/javascript/index.js"],
+entryPoints: ["./frontend/javascript/index.js"],
```

**Comment by jaredcwhite** [comment]
@andrewmcodes @KonnorRogers OK I've added in the `./` at the start of the entryPoint, hopefully that's all we need to worry about.

**Pull request merged**
