### PR TITLE
Add modules resolve paths to default webpack config

### PR DESCRIPTION
**Pull request by ayushn21**
- [x] I've adjusted the documentation (if it's a feature or enhancement)
- [x] The test suite passes locally (run `script/cibuild` to verify this)

## Summary

This PR adds 3 paths to Webpack's default module resolution list. This means that JS modules located in the following directories can be `import`ed or `require`d without specifying the full or relative paths.

* `frontend/javascript`
* `frontend/styles`
* `src/_components`

I also changed the documentation on the **Components** page to indicate that JS modules located there can be imported without specifying the path.

I know the current description describes a configuration where all JS files in the `_components` directory would be autoloaded.  But since those files can now be `import`ed with 0 config, I thought changing it was the more user-friendly approach. I'm happy to revert/rework the docs as per feedback though. Just did what I personally thought was appropriate!

## Context

https://github.com/bridgetownrb/bridgetown/issues/29#issuecomment-732454477

### CODE REVIEW

**Comment by jaredcwhite** [comment]
I feel like the "sidecar JS assets" for components should just automatically load, since ideally every component's JS is independent thus the load order is irrelevant. Sort of like how Stimulus JS controllers all autoload as well.

Other than that, I approve these changes. :+1:

**Comment by ayushn21** [comment]
Hmmm, yeah I agree that experience would be better. I'll update the PR soon :)

**Comment by ayushn21** [comment]
The way I see it, if we want to autoload all `.js` files in `_components`, adding that directory to the search paths doesn't make a lot of sense as we'll never be manually `import`ing files from there.

In my last commit, I just took the approach currently on the Bridgetown website to import all component `js` files and added it to the default template so the developer doesn't have to do anything.

So the PR adds `frontend/styles` and `frontend/javascript` to the module search paths so the developer can `import` modules from those directories without specifying the path. It also adds a couple of lines to `frontend/javascript/index.js` to autoload all `js` files from `src/_components`.

What do you feel about this approach @jaredcwhite?

**Comment by jaredcwhite** [comment]
This looks great @ayushn21! I'd forgotten about that example code to add the `liquidComponents` alias…and actually we're in the process of transitioning away from _only_ Liquid components to a polyglot configuration so that should probably be renamed to something else. `components` is likely too generic by itself. `srcComponents`? `localComponents`? Hmm…

**Comment by ayushn21** [comment]
Hmmm tricky one. How about just `components`? Or `bridgetownComponents`?

**Comment by jaredcwhite** [comment]
`bridgetownComponents` sounds good to me…no obvious collision with any other package names that might surface.

**Comment by ayushn21** [comment]
Cool! Was thinking a bit more and also thought of `viewComponents` but that I guess would clash with https://github.com/github/view_component.

How about `bridgetownViewComponents` or do you think `bridgetownComponents` is better?

**Comment by jaredcwhite** [comment]
> How about `bridgetownViewComponents` or do you think `bridgetownComponents` is better?

That is a little wordy…I think either `viewComponents` or `bridgetownComponents` is good, leaning towards the latter.

**Comment by ayushn21** [comment]
Cool; I like `bridgetownComponents` as well so will make that update

**Comment by ayushn21** [comment]
@jaredcwhite I've renamed the components alias. I reckon it's pretty much good to go :)

**Comment by jaredcwhite** [comment]
LGTM! :+1:

**Pull request merged**
